/yantra:
  gazebo_ros_control:
    pid_gains:
      joint_0_1: &joint_0_1_gains
        p: 100.0
        i: 0.1
        d: 25.0
      joint_1_2: &joint_1_2_gains
        p: 300.0
        i: 2.0
        d: 100.0
      joint_2_3: &joint_2_3_gains
        p: 900.0
        i: 1.0
        d: 200.0
      joint_3_4: &joint_3_4_gains
        p: 5.0
        i: 0.1
        d: 0.5
      joint_4_51: &joint_4_51_gains
        p: 200.0
        i: 5.0
        d: 60.0

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    joints: 
      - joint_0_1
      - joint_1_2
      - joint_2_3
      - joint_3_4
      - joint_4_51

  link_one_controller:
    type: velocity_controllers/JointGroupVelocityController
    joint: joint_0_1
    pid: {p: 100.0, i: 0.1, d: 25.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

  link_two_controller:
    type: velocity_controllers/JointGroupVelocityController
    joint: joint_1_2
    pid: {p: 300.0, i: 2.0, d: 100.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

  link_three_controller:
    type: velocity_controllers/JointGroupVelocityController
    joint: joint_2_3
    pid: {p: 900.0, i: 1.0, d: 200.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

  link_four_controller:
    type: velocity_controllers/JointGroupVelocityController
    joint: joint_3_4
    pid: {p: 5.0, i: 0.1, d: 0.5, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

  link_five_controller:
    type: velocity_controllers/JointGroupVelocityController
    joint: joint_4_51
    pid: {p: 200.0, i: 5.0, d: 60.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}




#  yantra_arm_controller:
#    type: velocity_controllers/JointGroupVelocityController
#    joints:
#      - joint_0_1
#      - joint_1_2
#      - joint_2_3
#      - joint_3_4
#      - joint_4_51

#    joint_0_1: 
#      pid: {p: 100.0, i: 0.1, d: 25.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
#    joint_1_2: 
#      pid: {p: 300.0, i: 2.0, d: 100.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
#    joint_2_3: 
#      pid: {p: 900.0, i: 1.0, d: 200.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
#    joint_3_4: 
#      pid: {p: 50.0, i: 0.1, d: 0.5, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
#    joint_4_51: 
#      pid: {p: 200.0, i: 5.0, d: 60.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

#  joint_limits:
#    joint_4_51:
#      has_position_limits: true
#      min_position: 0.0
#      max_position: 1.0
#      has_velocity_limits: true
#      max_velocity: 2.0
#      has_acceleration_limits: true
#      max_acceleration: 5.0
#      has_jerk_limits: true
#      max_jerk: 10.0
#      has_effort_limits: true
#      max_effort: 5.0
#      
      
      
      
